CREATE SEQUENCE  "SEQ_MPBT_FILE_INFO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
/

CREATE SEQUENCE  "SEQ_MPBT_THREAD_INFO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
/

CREATE SEQUENCE  "SEQ_MPBT_NOTICE_INFO"  MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
/

CREATE TABLE "MPBT_FILE_INFO"
   ("ID" NUMBER(18,0) NOT NULL,
	"F_NAME" NVARCHAR2(512) NOT NULL,
	"F_PATH" VARCHAR2(512 BYTE) NOT NULL,
	"F_SIZE" NUMBER(18,0) NOT NULL,
	"REG_ID" NUMBER(18,0) NOT NULL,
	"REG_DT" TIMESTAMP (6) DEFAULT systimestamp,
	CONSTRAINT pk_MPBT_FILE_INFO PRIMARY KEY(ID)
   ) ;
/

CREATE TABLE "MPBT_THREAD_INFO"
   ("ID" NUMBER(18,0) NOT NULL,
	"CREATOR" NUMBER(18,0) NOT NULL,
	"SUBJECT" NVARCHAR2(512) NOT NULL,
	"REG_ID" NUMBER(18,0) NOT NULL,
	"REG_DT" TIMESTAMP (6) DEFAULT systimestamp,
	CONSTRAINT pk_MPBT_THREAD_INFO PRIMARY KEY(ID)
   ) ;
/

CREATE TABLE "MPBT_NOTICE_INFO"
   ("ID" NUMBER(18,0) NOT NULL,
	"SENDER" NUMBER(18,0) NOT NULL,
	"CONTENTS" NCLOB NOT NULL,
	"REG_ID" NUMBER(18,0) NOT NULL,
	"REG_DT" TIMESTAMP (6) DEFAULT systimestamp,
	CONSTRAINT pk_MPBT_NOTICE_INFO PRIMARY KEY(ID)
   ) ;
/

CREATE TABLE "MPBT_THREAD_NOTICE_REL_INFO"
   ("THREAD_ID" NUMBER(18,0) NOT NULL,
	"NOTICE_ID" NUMBER(18,0) NOT NULL,
	CONSTRAINT pk_MPBT_THREAD_NOTICE_REL_INFO PRIMARY KEY(THREAD_ID, NOTICE_ID)
   ) ;
/

CREATE TABLE "MPBT_NOTICE_RECEIVER_REL_INFO"
   ("NOTICE_ID" NUMBER(18,0) NOT NULL,
	"RECEIVER" NUMBER(18,0) NOT NULL,
	CONSTRAINT pk_MPBT_NOTICE_RECEIVER_REL_INFO PRIMARY KEY(NOTICE_ID, RECEIVER)
   ) ;
/

CREATE TABLE "MPBT_NOTICE_ATTACH_REL_INFO"
   ("NOTICE_ID" NUMBER(18,0) NOT NULL,
	"FILE_ID" NUMBER(18,0) NOT NULL,
	CONSTRAINT pk_MPBT_NOTICE_ATTACH_REL_INFO PRIMARY KEY(NOTICE_ID, FILE_ID)
   ) ;
/

CREATE TABLE "MPBT_PUSH_HISTORY" (
	"SENDER" NUMBER(18,0) NOT NULL,
	"RECEIVER" NUMBER(18,0) NOT NULL,
	"SENDER_OS_TYPE" VARCHAR2(10 BYTE) NOT NULL,
	"RECEIVER_OS_TYPE" VARCHAR2(10 BYTE) NOT NULL,
	"PAYLOAD_TYPE" VARCHAR2(50 BYTE) NOT NULL,
	"PAYLOAD_ATTRS" VARCHAR2(512 BYTE) NOT NULL,
	"SENT_YN" CHAR(1 BYTE) NOT NULL,
	"REG_DT" TIMESTAMP (6) DEFAULT systimestamp
   );
/

CREATE INDEX "IX_MPBT_PUSH_HISTORY" ON "MPBT_PUSH_HISTORY" ("SENDER", "RECEIVER", "RECEIVER_OS_TYPE", "SENT_YN", "REG_DT");
/