domain: m-talk.gsc

activemq:
#    url: failover:(tcp://10.1.3.91:61616?connectionTimeout=3000)?randomize=false&timeout=1000&maxReconnectAttempts=3&initialReconnectDelay=100
#    url: tcp://10.1.3.91:61616?connectionTimeout=3000&jms.useAsyncSend=true&jms.optimizeAcknowledge=true
    url: tcp://10.1.3.91:61616?connectionTimeout=3000&jms.useAsyncSend=true&jms.optimizeAcknowledge=true&jms.alwaysSessionAsync=false
    pool-size: 10

database:
    name: mssql
    #driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #url: jdbc:sqlserver://10.1.3.132:1432;DatabaseName=GSC;sendStringParametersAsUnicode=false;
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:sqlserver://10.1.3.132:1432;DatabaseName=GSC;sendStringParametersAsUnicode=false;
    #username: pps
    #password: pps123!@#
    username: ENC(zUaqJDwtiT27h9HJQLlJmg==)
    password: ENC(6OZNjZZRbJcV2l5lJD8GkYutZh4IfmAN)
    pool-init-size: 5
    pool-max-size: 20

ps:
    name: ps-2
    ip: 10.1.3.91
    tas:
        port: 14008
    web:
        port: 8084
    temp:
        dir: /app/gsc/ps-2/temp

keystore:
    fcm:
        url: file:config/keystore/fcm-private-key-tionsoft.json