domain: m-talk.gsc

activemq:
    url: failover:(tcp://10.1.3.130:61616?connectionTimeout=3000)?randomize=false&timeout=1000&maxReconnectAttempts=3&initialReconnectDelay=100
    pool-initial-size: 20

database:
    name: mssql
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.1.3.132:1432;DatabaseName=GSC;sendStringParametersAsUnicode=false;
    username: pps
    password: pps123!@#
    pool-init-size: 5
    pool-max-size: 20

ps:
    name: ps-2
    ip: 10.1.3.91
    tas:
        port: 15008
    web:
        port: 8082
    temp:
        dir: /app/gsc/ps/temp